config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :trainings
  resources :workouts do 
    resources :trainings, shallow: true
    end
  resources :events do 
    resources :trainings, shallow: true
    end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :trainings, dependent: :destroy
  has_many :events, through: :trainings
  validates_associated :trainings
  validates :name, uniqueness: true
  validates :category, :duration, :intensity, presence: true
  validates :duration, numericality: true
  validates :intensity, numericality: { greater_than: 0, less_than: 6 }

# scope method
  scope :most_popular, -> { Workout.left_outer_joins(:trainings).group(:id).order("count(trainings.workout_id) desc") }
  # want to order the 'all workouts' view by popularity (i.e. number of trainings associated with that workout)
  # to count the number of trainings of an associated workout => @workout.trainings.count
  # .order -- desc  (i.e. "descending")
  # because it involves a join table, we have to incorporate joins + model into the scope method

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    
    def index
        @workouts = Workout.most_popular
        # replaced .all with workout scope method .most_popular
    end

    def new
        @workout = Workout.new
    end

    def create
        @workout = current_user.created_workouts.build(workout_params)
        if @workout.save
            redirect_to workout_path(@workout)
        else
            render :new
        end
    end

    def show
        @workout = Workout.find_by(id: params[:id])
    end

    def edit
        @workout = Workout.find_by(id: params[:id])
    end

    def update
        @workout = Workout.find_by(id: params[:id])
        if @workout.update(workout_params)
            redirect_to @workout
          else
            render 'edit'
          end
    end

    def destroy
        @workout = Workout.find_by(id: params[:id])
        @workout.destroy
        redirect_to workouts_path
    end

    private

    def workout_params
        params.require(:workout).permit(:name, :category, :duration, :intensity, :user_id)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/index.html.erb
<h1>All Workouts</h1>
<p>Here are some popular workouts that you might try:</p>

<br></br>

<table>
    <thead>
        <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Duration</th>
        <th>Intensity</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <% @workouts.each do |workout| %>

    <tr>
    <td><%= workout.name  %></td>
    <td><%= workout.category %></td>
    <td><%= workout.duration %></td>
    <td><%= workout.intensity %></td>
    <td><%= link_to 'Details', workout_path(workout) %></td>
    <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
    <td><%= link_to 'Delete', workout_path(workout), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    
    <% end %>
</tbody>
</table>

<br></br>

<%= link_to 'Add a New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>Add a New Workout</h1>

<%= render partial: "layouts/errors", locals: { object: @workout } %>

<%= form_for @workout do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :category %>
<%= f.select :category, options_for_select(["Circuit", "Run", "Cross Fit", "Bike", "Swim", "Other"]), include_blank: true %>
<br>
<br>
<%= f.label :duration %>
<%= f.text_field :duration %> In minutes
<br>
<br>
<%= f.label :intensity %>
<%= f.text_field :intensity %> On a scale of 1 to 5 (5 = most difficult)
<br>
<br>
<%= f.submit('Add')%>   |   <%= link_to 'Cancel', workouts_path %>

<% end %>

app/views/workouts/show.html.erb
<h1><%= @workout.name %></h1>

<strong>Category:</strong> <%= @workout.category %><br>
<strong>Duration:</strong> <%= @workout.duration %> minutes<br>
<strong>Intensity:</strong> <%= @workout.intensity %> (1=easy, 5=difficult)
<br>
<br>
<strong>Number of Times You've Done this Workout: </strong><%= @workout.trainings.count %>
<br></br>
<%= link_to 'Return to All Workouts', workouts_path %>