config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :trainings
  resources :workouts do 
    resources :trainings, shallow: true
    end
  resources :events do 
    resources :trainings, shallow: true
    end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :created_workouts, foreign_key: "user_id", class_name: "Workout"
    # this is the relationship where the user creates the workout him/herself; no repeats
    has_many :events
    has_many :trainings, through: :events
    has_many :completed_workouts, through: :events, source: :workouts
    # this refers to the relationship where the user did this workout in preparation for a specific event; may have repeats with this one
    has_secure_password
    validates :username, :email, presence: true
    validates :username, uniqueness: true 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :redirect_if_not_logged_in, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to events_path
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by(id: params[:id])
        redirect_to '/' if !@user 
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>New User Signup</h1>

<%= render partial: "layouts/errors", locals: { object: @user } %>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit('Signup') %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username%></h1>
<div class="wrapper">
<div class="card" style="width: 10rem;">
  <div class="card-body">
    <h3 class="card-title">Events</h3>
    <p class="card-text">Add an event for which you'd like to start training!</p>
    <%= link_to 'Add an Event', new_event_path %>   |   <%= link_to 'My Events', events_path %>
  </div>
</div>

<div class="card" style="width: 10rem;">
  <div class="card-body">
    <h3 class="card-title">Workouts</h3>
    <p class="card-text">Record a workout or get inspiration from other users.</p>
    <%= link_to 'Record a Workout', new_workout_path %>   |   <%= link_to 'All Workouts', workouts_path %>
  </div>
</div>

<div class="card" style="width: 10rem;">
  <div class="card-body">
    <h3 class="card-title">Trainings</h3>
    <p class="card-text">Record a training to keep track of your progress.</p>
    <%= link_to 'Record a Training', new_training_path %>   |   <%= link_to 'My Trainings', workouts_path %>
  </div>
</div>

</div>