config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :trainings
  resources :workouts do 
    resources :trainings, shallow: true
    end
  resources :events do 
    resources :trainings, shallow: true
    end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :trainings
  has_many :workouts, through: :trainings
  validates :title, :category, :description, :length, presence: true
  validates :length, numericality: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
    end
    
    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            redirect_to events_path
        else
            render :new
        end
    end

    def show
        @event = Event.find_by(id: params[:id])
    end

    def edit
        @event = Event.find_by(id: params[:id])
    end

    def update
        @event = Event.find_by(id: params[:id])
        if @event.update(event_params)
            redirect_to @event
          else
            render 'edit'
          end
    end

    def destroy
        @event = Event.find_by(id: params[:id])
        @event.destroy
        redirect_to events_path
    end

    private

    def event_params
        params.require(:event).permit(:title, :category, :description, :length)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1>Your Events</h1>

<% if current_user.events.exists? %>
<table>
    <thead>
        <tr>
        <th>Title</th>
        <th>Category</th>
        <th>Description</th>
        <th>Length</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <% current_user.events.each do |event| %>
        <tr>
            <td><%= event.title  %></td>
            <td><%= event.category %></td>
            <td><%= event.description %></td>
            <td><%= event.length %></td>
            <td><%= link_to 'Details', event_path(event) %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Delete', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
   
    <% else %>
        <p>You have no upcoming events. </p>
    <% end %>
    
<br></br>

<%= link_to 'Add a New Event', new_event_path %>

app/views/events/new.html.erb
<h1>Add a New Event</h1>

<%= render partial: "layouts/errors", locals: { object: @event } %>

<%= form_for(@event) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<br>
<%= f.label :category %>
<%= f.select :category, options_for_select(["Race", "Obstacle Course", "Triathlon", "Other"]), include_blank: true %>
<br>
<br>
<%= f.label :description %>
<%= f.text_field :description %>
<br>
<br>
<%= f.label :length %>
<%= f.text_field :length %>
<br>
<br>
<%= f.submit('Add')%>   |   <%= link_to 'Cancel', events_path %>

<% end %>

app/views/events/show.html.erb
<h1><%= @event.title%></h1>

<strong>Category:</strong> <%= @event.category %><br>
<strong>Description:</strong> <%= @event.description %><br>
<strong>Event Length:</strong> <%= @event.length %> miles
<br>
<br>
<%= link_to 'Return to My Events', events_path %>