config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :trainings
  resources :workouts do 
    resources :trainings, shallow: true
    end
  resources :events do 
    resources :trainings, shallow: true
    end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %> prohibited this training from being saved:</h2>

        <ul>
        <% object.errors.full_messages.each do |m| %>
        <li><%= m %> </li>
    <% end %>
        </ul>
        </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if logged_in? %>
      <%= link_to "Home", root_path %>    |    
      <%= link_to "Events", events_path %>    |    
      <%= link_to "Workouts", workouts_path %>    |    
      <%= link_to "Trainings", trainings_path %>    |    
      <%= link_to "Logout", logout_path, method: 'delete' %>
     <% else %>
      <%= link_to "Sign Up", signup_path %>    |    
      <%= link_to "Login", login_path %>
      <% end %>
    </div>

    
    <%= yield %>
  </body>
</html>